"""
ai_insights.py
Day 3 Morning: Executive summary, recommendations, and anomaly explanations —
all generated by an LLM call on top of numbers you already computed
(profiler.py / anomaly.py). The LLM never invents figures; it only narrates
the stats you pass in.
"""

import os

import pandas as pd
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

MODEL_NAME = "openai/gpt-oss-120b"  # match whatever model your llm_client.py uses


def _get_client() -> Groq:
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError("GROQ_API_KEY is not set. Add it to your .env file.")
    return Groq(api_key=api_key)


def _ask(system_prompt: str, user_prompt: str) -> str:
    client = _get_client()
    response = client.chat.completions.create(
        model=MODEL_NAME,
        temperature=0.3,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    )
    return response.choices[0].message.content.strip()


def generate_executive_summary(profile_stats: dict, column_profile_df: pd.DataFrame) -> str:
    """
    3-4 sentence business-facing summary of the dataset: size, shape, and
    anything notable about data quality. Grounded only in the numbers passed in.
    """
    profile_text = column_profile_df.to_string(index=False)
    prompt = f"""Dataset overview:
Rows: {profile_stats['row_count']}
Columns: {profile_stats['column_count']}
Missing values: {profile_stats['missing_values']}
Duplicate rows: {profile_stats['duplicate_rows']}

Column profile:
{profile_text}

Write a concise 3-4 sentence executive summary of this dataset for a business
audience. Mention data size, general shape, and anything notable about data
quality (missingness, duplicates, low-variance columns). Use ONLY the numbers
given above — never invent figures."""
    return _ask("You are a data analyst writing a summary for business stakeholders.", prompt)


def generate_recommendations(
    profile_stats: dict,
    anomaly_summary_df: pd.DataFrame,
    chat_history: list,
) -> str:
    """
    3-5 bullet-point recommendations based on data quality stats, detected
    anomalies, and what's been asked so far in the AI Analysis tab.
    """
    anomaly_text = (
        anomaly_summary_df.to_string(index=False)
        if anomaly_summary_df is not None and not anomaly_summary_df.empty
        else "No anomalies were flagged."
    )
    questions_asked = (
        "\n".join(f"- {turn['question']}" for turn in chat_history)
        if chat_history
        else "No questions have been asked yet."
    )
    prompt = f"""Dataset stats:
Rows: {profile_stats['row_count']}, Missing values: {profile_stats['missing_values']}, Duplicates: {profile_stats['duplicate_rows']}

Anomaly summary (per column):
{anomaly_text}

Questions already explored by the user:
{questions_asked}

Write 3-5 concise, actionable recommendations for someone working with this
dataset. Base them only on the information above — data quality issues worth
fixing, columns worth investigating further, or natural next questions to ask.
Format as a markdown bullet list."""
    return _ask("You are a senior data analyst giving practical next steps.", prompt)


def explain_anomalies(anomaly_summary_df: pd.DataFrame, method: str) -> str:
    """
    Plain-English explanation of what the flagged anomalies might mean and
    what to check next. One combined call across all flagged columns.
    """
    if anomaly_summary_df is None or anomaly_summary_df.empty:
        return "No anomalies were detected with the current settings."

    flagged = anomaly_summary_df[anomaly_summary_df["anomaly_count"] > 0]
    if flagged.empty:
        return "No anomalies were detected with the current settings."

    prompt = f"""Anomaly detection method used: {method}

Per-column anomaly counts:
{flagged.to_string(index=False)}

In plain English, explain what these flagged anomalies likely mean for
someone exploring this dataset, and suggest 2-3 concrete things to check
next for the column(s) with the most anomalies. Do not invent details about
the data beyond what's shown above — speak in general terms about what this
pattern of outliers could indicate."""
    return _ask("You explain statistical anomaly results in plain English.", prompt)